schema: "classroom50/repo-config/v1"
classroom: "agi"
assignment: "todo"
owner:
  username: "s25009-gif"
  id: 321209335
  accepted_at: "2026-09-08T23:54:07Z"
source:
  owner: "gsm-class"
  owner_id: 318515310
  repo: "todo"
  branch: "main"
